/**
 * Inline USD amount conversion for Korean copy.
 *
 * Many bioKo strings were generated by an LLM that left dollar figures as
 * "35억 달러" / "1.5조 달러" / "100억 달러" etc — accurate in USD but
 * jarring next to the page header where we already render the same number
 * in 조원 / 억원. This module rewrites those inline mentions to match the
 * Korean won figure derived from the person's `netWorth` so both numbers
 * line up.
 *
 * Why text replacement at render time (not in the data):
 *   - The data file is the source of truth and the underlying $ figure is
 *     factually correct — we don't want to lose it on disk.
 *   - LLMs occasionally write "$3.5B" / "약 35억 달러" / "1.5조 달러" / etc.
 *     with subtly different phrasings; a single regex pass at render is
 *     easier to extend than a one-off migration.
 *   - Keeps locale flexibility: an English render can still show "$3.5B".
 *
 * The conversion target is always the person's `netWorth` (billions USD),
 * because that's the number the rest of the UI displays. So if a bio says
 * "$2.8 billion" but the person record's netWorth is 3.5, we use 3.5.
 * (Otherwise the page would advertise two different totals, which is the
 * exact problem we're solving.)
 */

const USD_TO_KRW = 1480.71;

/**
 * Format a net-worth value (in billions USD) as a "X.X조원" / "X억원"
 * string matching the headline elsewhere on the page.
 *
 * Examples:
 *   3.5  → "약 5.2조원"
 *   0.95 → "약 1.4조원" (still expresses as 조 since it's >= 1 trillion KRW)
 *   0.05 → "약 740억원" (sub-trillion lands in 억 instead)
 */
export function formatKrwApprox(netWorthBillions: number): string {
  const eok = netWorthBillions * 10 * USD_TO_KRW; // 100M USD → 1조원 (rough)
  const jo = eok / 10000;
  if (jo >= 1) {
    const rounded = jo >= 10 ? Math.round(jo) : Number(jo.toFixed(1));
    return `약 ${rounded}조원`;
  }
  return `약 ${Math.round(eok).toLocaleString('ko-KR')}억원`;
}

/**
 * Rewrite USD mentions inside a Korean text blob to the won figure derived
 * from `netWorthBillions`. Conservative — only touches patterns that are
 * clearly stating a net-worth-like amount in dollars:
 *
 *   "$3.5 billion"        / "$3.5B"          / "$3.5 billion 달러"
 *   "35억 달러"           / "약 35억 달러"   / "350억 달러"
 *   "1.5조 달러"          / "약 1.5조 달러"
 *
 * Anything that doesn't match these patterns is left alone, so prose like
 * "수십억 달러 규모" or "$10 million" stays as written.
 *
 * The replacement always uses the person's headline net worth — this is
 * intentional: a bio that says "재산이 35억 달러" but where the person's
 * record net worth is 5.2조원 should sync to 5.2조원, not "약 4.7조원"
 * (the literal 35억$ figure). The whole point is to stop the bio and the
 * header from disagreeing.
 */
export function rewriteUsdToKrwInline(text: string, netWorthBillions: number): string {
  if (!text || !Number.isFinite(netWorthBillions) || netWorthBillions <= 0) return text;
  const krw = formatKrwApprox(netWorthBillions);

  // Each pattern is anchored with optional "약 " prefix so we don't double
  // up the modifier (the replacement always carries its own "약 ").
  const patterns: RegExp[] = [
    // "$3.5 billion" / "$3.5B" / "US$3.5 billion"
    /(?:약\s*)?(?:US\s*)?\$\s*[\d.,]+\s*(?:billion|B)\b\s*달러?/gi,
    // "$3.5 trillion" / "$3.5T"
    /(?:약\s*)?(?:US\s*)?\$\s*[\d.,]+\s*(?:trillion|T)\b\s*달러?/gi,
    // "35억 달러" / "약 35억 달러"
    /(?:약\s*)?[\d.,]+\s*억\s*달러/g,
    // "1.5조 달러" / "약 1.5조 달러"
    /(?:약\s*)?[\d.,]+\s*조\s*달러/g,
    // "1.5십억 달러" — old translation artifact for "1.5 billion"
    /(?:약\s*)?[\d.,]+\s*십억\s*달러/g,
  ];

  let out = text;
  for (const re of patterns) {
    out = out.replace(re, krw);
  }
  return out;
}
