import * as fs from 'fs';
import { billionaires } from '../src/lib/data/billionaires';

// Map of name -> company/source of wealth
const SOURCE_MAP: Record<string, string> = {
  'Elon Musk': 'Tesla, SpaceX',
  'Jeff Bezos': 'Amazon',
  'Bernard Arnault': 'LVMH',
  'Mark Zuckerberg': 'Meta (Facebook)',
  'Larry Ellison': 'Oracle',
  'Warren Buffett': 'Berkshire Hathaway',
  'Bill Gates': 'Microsoft',
  'Steve Ballmer': 'Microsoft',
  'Mukesh Ambani': 'Reliance Industries',
  'Larry Page': 'Google (Alphabet)',
  'Sergey Brin': 'Google (Alphabet)',
  'Michael Bloomberg': 'Bloomberg LP',
  'Jensen Huang': 'NVIDIA',
  'Carlos Slim': 'Telmex, America Movil',
  'Francoise Bettencourt Meyers': "L'Oreal",
  'Amancio Ortega': 'Zara (Inditex)',
  'Jim Walton': 'Walmart',
  'Rob Walton': 'Walmart',
  'Alice Walton': 'Walmart',
  'Michael Dell': 'Dell Technologies',
  'Charles Koch': 'Koch Industries',
  'Julia Koch': 'Koch Industries',
  'Zhong Shanshan': 'Nongfu Spring',
  'Phil Knight': 'Nike',
  'Gautam Adani': 'Adani Group',
  'Ma Huateng': 'Tencent',
  'Jack Ma': 'Alibaba',
  'Zhang Yiming': 'ByteDance (TikTok)',
  'David Thomson': 'Thomson Reuters',
  'Dieter Schwarz': 'Lidl, Kaufland',
  'Giovanni Ferrero': 'Ferrero (Nutella)',
  'Tadashi Yanai': 'Uniqlo (Fast Retailing)',
  'Len Blavatnik': 'Access Industries',
  'Takemitsu Takizaki': 'Keyence',
  'Stephen Schwarzman': 'Blackstone',
  'Ken Griffin': 'Citadel',
  'Masayoshi Son': 'SoftBank',
  'Li Ka-shing': 'CK Hutchison',
  'Rupert Murdoch': 'Fox, News Corp',
  'Lee Shau-kee': 'Henderson Land',
  'Alain Wertheimer': 'Chanel',
  'Gerard Wertheimer': 'Chanel',
  'Jacqueline Mars': 'Mars Inc.',
  'John Mars': 'Mars Inc.',
  'Klaus-Michael Kuehne': 'Kuehne+Nagel',
  'Miriam Adelson': 'Las Vegas Sands',
  'William Ding': 'NetEase',
  'Colin Zheng Huang': 'Pinduoduo (PDD)',
  'Thomas Peterffy': 'Interactive Brokers',
  'Susanne Klatten': 'BMW (inherited)',
  'Ray Dalio': 'Bridgewater Associates',
  'MacKenzie Scott': 'Amazon (ex-spouse)',
  'George Soros': 'Soros Fund Management',
  'Abigail Johnson': 'Fidelity Investments',
  'Robin Zeng': 'CATL',
  'Li Shufu': 'Geely Auto',
  'Shiv Nadar': 'HCL Technologies',
  'Lakshmi Mittal': 'ArcelorMittal',
  'He Xiangjian': 'Midea Group',
  'Stefan Quandt': 'BMW',
  'Wang Chuanfu': 'BYD',
  'Peter Woo': 'Wheelock & Co.',
  'Dietrich Mateschitz': 'Red Bull',
  'Azim Premji': 'Wipro',
  'Wang Wei': 'SF Express',
  'Pang Kang': 'Foshan Haitian',
  'Richard Branson': 'Virgin Group',
  'Jack Dorsey': 'Twitter, Block',
  'Brian Chesky': 'Airbnb',
  'Lei Jun': 'Xiaomi',
  'Dhanin Chearavanont': 'CP Group',
  'Charlene de Carvalho-Heineken': 'Heineken',
  'Gina Rinehart': 'Hancock Prospecting',
  'Andrew Forrest': 'Fortescue Metals',
  'Nicky Oppenheimer': 'De Beers',
  'Johann Rupert': 'Richemont (Cartier)',
  'German Larrea': 'Grupo Mexico',
  'Lee Jae-yong': 'Samsung',
  'Chung Mong-koo': 'Hyundai Motor',
  'Kim Beom-su': 'Kakao',
  'Seo Jung-jin': 'Celltrion',
  'Jay Y. Lee': 'Samsung',
  'Bang Si-hyuk': 'HYBE (BTS)',
  'Kwon Hyuk-bin': 'Smilegate',
  'Kim Jung-ju': 'Nexon',
  'Chey Tae-won': 'SK Group',
  'Shin Dong-bin': 'Lotte Group',
  'Patrick Drahi': 'Altice',
  'Francois Pinault': 'Kering (Gucci)',
  'Iris Fontbona': 'Antofagasta',
  'Peter Thiel': 'PayPal, Palantir',
  'Reed Hastings': 'Netflix',
  'Marc Benioff': 'Salesforce',
  'Travis Kalanick': 'Uber',
  'Evan Spiegel': 'Snap (Snapchat)',
  'Bobby Murphy': 'Snap (Snapchat)',
  'Sam Altman': 'OpenAI',
  'Liu Qiangdong': 'JD.com',
  'Wang Xing': 'Meituan',
  'Su Hua': 'Kuaishou',
  'Oprah Winfrey': 'Harpo Productions',
  'Giorgio Armani': 'Armani',
  'Ralph Lauren': 'Ralph Lauren Corp.',
  'Leonardo Del Vecchio': 'Luxottica (Ray-Ban)',
  'Reinhold Wuerth': 'Wuerth Group',
  'Hasso Plattner': 'SAP',
  'Daniel Ek': 'Spotify',
  'Dustin Moskovitz': 'Facebook, Asana',
  'Eduardo Saverin': 'Facebook',
  'Sean Parker': 'Napster, Facebook',
  'Meg Whitman': 'eBay, HP',
  'Marissa Mayer': 'Google, Yahoo',
  'Eric Schmidt': 'Google',
  'Tim Cook': 'Apple',
  'Satya Nadella': 'Microsoft',
  'Sundar Pichai': 'Google (Alphabet)',
  'Jamie Dimon': 'JPMorgan Chase',
  'Carl Icahn': 'Icahn Enterprises',
  'George Lucas': 'Lucasfilm (Star Wars)',
  'Steven Spielberg': 'Amblin Entertainment',
  'David Geffen': 'DreamWorks',
  'Patrick Collison': 'Stripe',
  'John Collison': 'Stripe',
  'Jan Koum': 'WhatsApp',
  'Tony Xu': 'DoorDash',
  'Stewart Butterfield': 'Slack',
  'Drew Houston': 'Dropbox',
  'Robert Kuok': 'Kuok Group',
  'Li Xiting': 'Mindray Medical',
  'Ren Zhengfei': 'Huawei',
  'Lee Kun-hee': 'Samsung',
  'Lee Boo-jin': 'Hotel Shilla',
  'Robert Kraft': 'New England Patriots',
  'Jerry Jones': 'Dallas Cowboys',
  'Steve Cohen': 'Point72',
  'David Tepper': 'Appaloosa Management',
  'James Simons': 'Renaissance Technologies',
  'John Paulson': 'Paulson & Co.',
  'Paul Tudor Jones': 'Tudor Investment',
  'Leon Black': 'Apollo Global',
  'Henry Kravis': 'KKR',
  'Tilman Fertitta': 'Landry\'s, Rockets',
  'Harold Hamm': 'Continental Resources',
  'Aerin Lauder': 'Estee Lauder',
  'Leonard Lauder': 'Estee Lauder',
  'Mark Cuban': 'Broadcast.com, Mavs',
  'Rihanna': 'Fenty Beauty',
  'Jay-Z': 'Roc Nation, D\'Ussé',
  'Kanye West': 'Yeezy',
  'Aliko Dangote': 'Dangote Group',
  'Mike Adenuga': 'Globacom',
  'Strive Masiyiwa': 'Econet',
  'Patrice Motsepe': 'African Rainbow Minerals',
  'Nassef Sawiris': 'OCI',
  'Naguib Sawiris': 'Orascom',
  'Joseph Safra': 'Banco Safra',
  'Jorge Paulo Lemann': '3G Capital (AB InBev)',
  'Ricardo Salinas Pliego': 'Grupo Elektra',
  'Manuel Villar': 'Vista Land',
  'Henry Sy': 'SM Investments',
  'Robert Budi Hartono': 'Bank Central Asia',
  'Michael Hartono': 'Djarum',
  'Charoen Sirivadhanabhakdi': 'Thai Beverage',
  'Quek Leng Chan': 'Hong Leong Group',
  'Zhang Zhidong': 'Tencent',
  'Yang Huiyan': 'Country Garden',
  'Qin Yinglin': 'Muyuan Foods',
  'Guo Guangchang': 'Fosun',
  'Sun Piaoyang': 'Hengrui Medicine',
  'Akio Nitori': 'Nitori Holdings',
  'Hiroshi Mikitani': 'Rakuten',
  'Yusaku Maezawa': 'Zozotown',
  'Vagit Alekperov': 'Lukoil',
  'Vladimir Potanin': 'Norilsk Nickel',
  'Leonid Mikhelson': 'Novatek',
  'Vladimir Lisin': 'NLMK',
  'Alisher Usmanov': 'Metalloinvest',
  'Roman Abramovich': 'Evraz, Chelsea FC',
  'Mikhail Fridman': 'Alfa Group',
  'Petr Kellner': 'PPF Group',
  'Daniel Kretinsky': 'EPH',
  'Rafaela Aponte-Diamant': 'MSC',
  'Silvio Berlusconi': 'Mediaset, AC Milan',
  'Miuccia Prada': 'Prada',
  'Kumar Birla': 'Aditya Birla Group',
  'Dilip Shanghvi': 'Sun Pharma',
  'Cyrus Poonawalla': 'Serum Institute',
  'Uday Kotak': 'Kotak Mahindra Bank',
  'Savitri Jindal': 'Jindal Group',
  'Radhakishan Damani': 'DMart',
  'Nandan Nilekani': 'Infosys',
  'N.R. Narayana Murthy': 'Infosys',
  'Kiran Mazumdar-Shaw': 'Biocon',
  'Yuri Milner': 'DST Global',
  'Pavel Durov': 'Telegram',
  'Emmanuel Besnier': 'Lactalis',
  'Xavier Niel': 'Free (Iliad)',
  'Rodolphe Saade': 'CMA CGM',
  'Ernesto Bertarelli': 'Serono',
  'Gianluigi Aponte': 'MSC',
  'Anders Holch Povlsen': 'Bestseller, Zalando',
  'Stefan Persson': 'H&M',
  'Ingvar Kamprad': 'IKEA',
  'Kim Taek-jin': 'NCSoft',
  'Chung Euisun': 'Hyundai Motor',
  'Lee Myung-hee': 'Samsung (family)',
  'Koo Kwang-mo': 'LG',
  'Lee Seo-hyun': 'Samsung (family)',
  'Brian Armstrong': 'Coinbase',
  'Changpeng Zhao': 'Binance',
  'Vitalik Buterin': 'Ethereum',
  'Reid Hoffman': 'LinkedIn',
  'Pierre Omidyar': 'eBay',
  'Wang Jianlin': 'Wanda Group',
  'Terry Gou': 'Foxconn',
  'Morris Chang': 'TSMC',
  'Goh Cheng Liang': 'Nippon Paint',
  'Forrest Li': 'Sea (Shopee)',
  'Tony Fernandes': 'AirAsia',
  'Joseph Tsai': 'Alibaba',
  'Mike Cannon-Brookes': 'Atlassian',
  'Scott Farquhar': 'Atlassian',
  'Anthony Pratt': 'Visy Industries',
  'Chip Wilson': 'Lululemon',
  'Tobias Lutke': 'Shopify',
  'Garrett Camp': 'Uber',
  'Vicky Safra': 'Banco Safra',
  'Galen Weston Jr': 'Loblaw, Selfridges',
  'Alexei Mordashov': 'Severstal',
  'Andrey Melnichenko': 'EuroChem, SUEK',
  'Mikhail Prokhorov': 'Norilsk Nickel',
  'James Dyson': 'Dyson',
  'Denise Coates': 'Bet365',
  'Prince Alwaleed': 'Kingdom Holding',
  'Shahid Khan': 'Flex-N-Gate, Jaguars',
  'Donald Bren': 'Irvine Company',
  'Sara Blakely': 'Spanx',
  'Whitney Wolfe Herd': 'Bumble',
  'Judy Faulkner': 'Epic Systems',
  'Thai Lee': 'SHI International',
  'Diane Hendricks': 'ABC Supply',
  'Michael Jordan': 'Nike/Jordan Brand',
  'LeBron James': 'NBA, SpringHill',
  'Tiger Woods': 'PGA Golf',
  'Roger Federer': 'Tennis, On',
  'Cristiano Ronaldo': 'Football, CR7',
  'Lionel Messi': 'Football',
  'Kim Kardashian': 'SKIMS, KKW',
  'Kylie Jenner': 'Kylie Cosmetics',
  'Taylor Swift': 'Music',
  'Beyonce': 'Music, Ivy Park',
  'Madonna': 'Music',
  'Paul McCartney': 'The Beatles',
  'Mick Jagger': 'Rolling Stones',
  'Simon Cowell': 'Syco Entertainment',
  'Kevin Systrom': 'Instagram',
  'Mike Krieger': 'Instagram',
  'Eric Yuan': 'Zoom',
  'Vlad Tenev': 'Robinhood',
  'Baiju Bhatt': 'Robinhood',
  'Logan Green': 'Lyft',
  'John Zimmer': 'Lyft',
  'Anthony Tan': 'Grab',
  'Ratan Tata': 'Tata Group',
  'Falguni Nayar': 'Nykaa',
  'Nita Ambani': 'Reliance (family)',
  'Anil Ambani': 'Reliance ADA',
  'Sachin Bansal': 'Flipkart',
  'Binny Bansal': 'Flipkart',
  'Nikhil Kamath': 'Zerodha',
  'Nithin Kamath': 'Zerodha',
  'Bob Iger': 'Disney',
  'Dana White': 'UFC',
  'Bom Kim': 'Coupang',
  'Dara Khosrowshahi': 'Uber',
  'Son Masayoshi': 'SoftBank',
  'Saad Hariri': 'Saudi Oger',
  'Lorenzo Fertitta': 'UFC, Red Rock',
  'Frank Fertitta III': 'Red Rock Resorts',
  'Stephen Ross': 'Related Companies',
  'John Malone': 'Liberty Media',
  'Stanley Druckenmiller': 'Duquesne Capital',
  'Jeff Yass': 'Susquehanna (SIG)',
  'Israel Englander': 'Millennium Management',
  'Gennady Timchenko': 'Gunvor',
  'Suleiman Kerimov': 'Polyus Gold',
  'Hussain Sajwani': 'DAMAC Properties',
  'Stef Wertheimer': 'Iscar',
  'John Menard Jr': 'Menards',
  'Luiza Trajano': 'Magazine Luiza',
  'Lee Hae-jin': 'Naver',
  'Park Hyeon-joo': 'Mirae Asset',
  'Shin Kyuk-ho': 'Lotte Group',
  'Cho Yang-ho': 'Korean Air',
  'Koo Bon-moo': 'LG',
  'Park Jung-ho': 'SK Telecom',
  'Lee Woo-hyun': 'OCI',
  'Kim Seung-youn': 'Hanwha',
  'Hong Ra-hee': 'Samsung (family)',
};

// Apply source to billionaires
const updated = billionaires.map((p) => {
  const source = SOURCE_MAP[p.name] || p.industry;
  return { ...p, source };
});

const lines = updated.map((p) => {
  const src = (p as any).source || '';
  return `  { id: '${p.id}', name: '${p.name.replace(/'/g, "\\'")}', birthday: '${p.birthday}', netWorth: ${p.netWorth}, nationality: '${p.nationality}', industry: '${p.industry}', gender: '${p.gender}', source: '${src.replace(/'/g, "\\'")}', photoUrl: '${p.photoUrl.replace(/'/g, "\\'")}' },`;
});

const output = `import { Person } from '../saju/types';

export const billionaires: Person[] = [
${lines.join('\n')}
];
`;

fs.writeFileSync('/Users/namu_1/sajubuja/src/lib/data/billionaires.ts', output);
console.log(`Updated ${updated.length} entries with source of wealth.`);
console.log(`Mapped: ${Object.keys(SOURCE_MAP).length}, Fallback to industry: ${updated.length - Object.keys(SOURCE_MAP).length}`);
